### ISSUE TITLE
Keplergl problem in Streamlit

### ISSUE THREAD

**Issue by mcharles96** [chrieke/streamlit-keplergl#1]
I can't deploy keplergl map in Streamlit when I use geopandas and movingpandas in my dataframe. When I only use original dataframe, with latitude and longitude data, works well, but when I use these libraries to analysis stop points and trajectories, I get an error.

Obs.: I used Jupyter to test and visualize the map, but the app is .py file made in VS Code.

![20210727_225154](https://user-images.githubusercontent.com/87387756/127250965-9e4dee18-5474-418c-9bf0-902017b6a65f.jpg)

**Comment by chrieke** [comment]
Hey @mcharles96 thanks for opening this issue! Looking through the additional screenshots you sent me on Twitter, I'm not sure if this in issue of this streamlit-keplergl component, but rather an issue of movingpandas + keplergl working together. Were you successful in running your example in the Jupyter notebook environment? 
If not, I think it would be better to ask for help in the movingpandas or keplergl communities. Maybe [this article](https://towardsdatascience.com/stop-detection-in-gps-tracks-movingpandas-keplergl-point-map-with-stops-duration-in-bird-664064b3ccbc) also helps to clarify the behaviour.

**Comment by chrieke** [comment]
@mcharles96 Were you able to solve the problem? Closing, please feel free to reopen if new info.

**Comment by bhupinders** [comment]
Hi @chrieke Thanks for the package. I am also getting the same error.

The following renders without any issues.
`map_1 = KeplerGl(height=400)`

But on adding any data, it fails.
`map_1 = KeplerGl(height=600, data={
        "gps": data
    })`

Where data is a pandas dataframe with lat/lon columns. the map_1 loads in jupyter without using streamlit.

The main error is: 
`AttributeError: 'str' object has no attribute '_geom'`

Which leads to: 
`TypeError: fig argument has to be a keplergl map object of type keplergl.KeplerGl!`

Any idea what might be going on here? (It doesn't work on first loading of the page also and not just reloading)

Thanks!

**Comment by bhupinders** [comment]
Somehow it works If I save the data to disk and read again. Maybe modified dataframes are not working due to some reason.
