### ISSUE TITLE
Map won't render with specified configuration

### ISSUE THREAD

**Issue by davisgiles** [chrieke/streamlit-keplergl#11]
Hi, I am trying to load a GeoJson dataset onto the map and I am able to do so successfully and view in a streamlit dashboard however when I specify a config in the KeplerGl() function call keplergl_static(my_map) nothing renders on the dashboard. I can run the same code in a Jupyter notebook and specify the config and the map renders as expected.

**Comment by chrieke** [comment]
Hi @davisgiles thank you for the report.

Added an [example with specified configuration](https://github.com/chrieke/streamlit-keplergl/blob/main/examples/streamlit-keplergl-example-with-config.py), this one works for me. Could you check and confirm please or provide the parameters for your example? Thank you.

**Comment by chrieke** [comment]
Closing, please reopen if the example does not solve it for you.
