### ISSUE TITLE
Interactions - Geocoder not working 

### ISSUE THREAD

**Issue by SebastianoF** [chrieke/streamlit-keplergl#12]
When navigating to interaction tab and turning on the geocoder the map disappears from the view.

![Screenshot 2022-11-11 at 18 39 48](https://user-images.githubusercontent.com/8709755/201408998-533b0190-e2c2-48d0-88df-84e0a41ad97a.png)

Any idea what could be the cause and how to fix it?

**Comment by chrieke** [comment]
Is this the same problem? https://github.com/chrieke/streamlit-keplergl/issues/10

**Comment by SebastianoF** [comment]
Closing the issue as duplicate of #10. I would be grateful for any update/plan to address it. If you have suggestions I could try and fix it.
