### ISSUE TITLE
Width does not update

### ISSUE THREAD

**Issue by robmarkcole** [chrieke/streamlit-keplergl#3]
Passing the `height` parameter achieved the desired result, but `width` does not. 

Also raised on https://discuss.streamlit.io/t/adapt-container-streamlit-keplergl/14821

**Comment by mykolakozyr** [comment]
Hey here as well @robmarkcole :)
I believe the width parameter works but in pixels only. 
I am looking for making it in percents. Is that the scope of this issue?

```
# Visualize in Streamlit
keplergl_static(w1, width=1200)
```
This actually makes it 1200 pixels wide

**Comment by mykolakozyr** [comment]
Btw, I have tested how it works with no width specified at all (I removed that in init.py) and looks like keplergl is smart to adjust to window width in a good way.
![](https://user-images.githubusercontent.com/17071295/149182074-ad4bfe36-26df-4d01-bb7f-60f446228fd1.gif)

It seems like it makes sense to remove width parameter at all and use streamlit layout tools to define width in pixels if needed

**Comment by chrieke** [comment]
@robmarkcole @mykolakozyr  Thank you for this great feedback! Finally looked into it and adjusted the behaviour, mainly removing the default values for width and height and fixing height adjustment, see PR above. Let me know if you encounter any issues with version 0.2.0!
