### ISSUE TITLE
Map does not locate on data

### ISSUE THREAD

**Issue by robmarkcole** [chrieke/streamlit-keplergl#4]
I created a demo app to load a geojson and can display fine, but the map always loads over San Fransisco. I think it may be because the dataframe is not passed using the `data` attribute? Unsure. 

```python3
import streamlit as st
from streamlit_keplergl import keplergl_static
from keplergl import KeplerGl
import geopandas as gpd

infile = 'data/my.json'

df = gpd.read_file(infile)
map_1 = KeplerGl(height=800)
map_1.add_data(df, 'data_1')
keplergl_static(map_1)

# Show data table
st.dataframe(df.drop(columns=['geometry']))
```

**Comment by mykolakozyr** [comment]
Hey @robmarkcole, you can use [keplergl config](https://docs.kepler.gl/docs/keplergl-jupyter#5.-save-and-load-config) to specify that. Indeed, the default one always opens in SF. I made it hardcoded for the global view, but you can do that dynamically by calculating those from GeoJSON.
I did not find any extensive documentation about config (probably I was not looking that good), so I used Kepler UI to create a map and then took a look at the config it generates (through the export map by json)

```
config = {
  "version":"v1",
  "config":{
    "mapState":{
         "bearing": 0,
         "latitude": 0.0,
         "longitude": 0.0,
         "pitch": 0,
         "zoom": 1
      }
   }
}
w1 = KeplerGl()
w1.config = config
```

**Comment by robmarkcole** [comment]
Thanks for the tip @mykolakozyr I guess I will leave this open as could be translated to a feature request potentially, although most likely a note in the readme/example would suffice

**Comment by chrieke** [comment]
Thank you both, added a short hint to the readme with a link to this thread. Will leave it open for now, not sure yet if this could be improved on this side or is just how Keplergl works.

**Comment by SebastianoF** [comment]
Any hint about how to retrieve the config file from the map on streamlit after changing the map?

On Jupiter notebook, if I navigate or change settings of `map_1`, in the cell below I can retrieve the current config with:
```
# Cell 1
map_1 = KeplerGl(data=kepler_data, height=800, config=initial_config)

# Here I play around with the with the map

# Cell 2
current_config = map_1.config
``` 
After this the `current_config` variable has the json/dict with the configuration of the current view, not the `initial_config` one.


If on Streamlit, with the map shown via `keplergl_static`, when asking current config via `map_1.config` this command returns always the initially given config, and not the one of the current view. 

### Example:
```
map_1 = KeplerGl(data=kepler_data, height=800, config=initial_config)
keplergl_static(map_1)

if st.button("show current config"): 
    current_config = map_1.config
    st.write(current_config)
```
If before pusing the button `"show current config"` I am changing the view, map, colour, or other things, when pushing the button I always have the `initial_config`, and I can not retrieve the current one, as I suspect the map on streamlit is completely detached from its view on streamlit. 

Ideally I would like to have something like a `get_current_config` method for the kepler_static instance:

```
map_1 = KeplerGl(data=kepler_data, height=800, config=initial_config)
ks = keplergl_static(map_1)

if st.button("show current config"):
    current_config = ks.get_current_config()
    st.write(current_config)
```

Is it already possible with some methods of `keplergl_static`?

Thank you!

**Comment by chrieke** [comment]
@SebastianoF The streamlit component is static, afaik there is no option to retrive information from/after a browser interaction. It would certainly be really helpful, there is a way to build interactive streamlit components. Could you maybe open a new issue and copy paste your description to separate the discussion, would like to close this issue.

**Comment by ghost** [comment]
found a very annoying bug as I was trying to implement this to streamlit. 

When you go to `interaction` and toggle on `geocoder` the app just crashes...

**Comment by chrieke** [comment]
@lennonzheng Thanks for reporting, will open a separate issue. Checked and can confirm that this only happens in the streamlit app, not in notebook.
