### ISSUE TITLE
New version did not work for me (windows user), map did not plot the data 

### ISSUE THREAD

**Issue by Cole-Narfason** [chrieke/streamlit-keplergl#6]
Hi there,

Just wanted to give you a heads up in case other people face the same issue. For some reason when I created a new virtual env in Anaconda and streamlit-keplergl was upgraded to the new version 0.2.0 my streamlit app stopped plotting the data altogether, but when reverted to 0.1.0 it started working as per usual. I have no idea why though as I am still pretty new to python/streamlit/kepler.

Cheeers,

Cole

**Comment by chrieke** [comment]
Thank you for the issue! Fixed in new version [0.3.0](https://github.com/chrieke/streamlit-keplergl/releases/tag/0.3.0)
