### ISSUE TITLE
Can not add data on the map

### ISSUE THREAD

**Issue by d-shiri** [chrieke/streamlit-keplergl#7]
Hi!
Using streamlit-keplergl, it works like the demo but when I add new data from a csv file, it does not show on the map. 
here is part of the code:
```python
with open(CONFIG, 'r') as stream:
  config = yaml.safe_load(stream)

data = pd.read_csv( 'file.csv')
st.dataframe(data.head())
# Build map finally
map = KeplerGl(height=800, data={NAME: data}, config=config)
```
note: this works on other environments like google colab and Jupiter. 
am I doing sth wrong?

**Comment by chrieke** [comment]
Thank you for the issue! Fixed in new version [0.3.0](https://github.com/chrieke/streamlit-keplergl/releases/tag/0.3.0)
